env:
  browser: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
settings:
  import/resolver: webpack
  import/extensions:
    - js
    - jsx
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-unused-vars:
    - warn
    -
      varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  no-console:
    - warn
