extends:
  - react-app
rules:
  array-bracket-spacing:
    - warn
  block-spacing:
    - warn
  brace-style:
    - warn
  camelcase:
    - warn
  comma-spacing:
    - warn
  eol-last:
    - warn
  func-call-spacing:
    - warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
  jsx-quotes:
    - warn
  linebreak-style:
    - error
    - unix
  no-console:
    - warn
  no-self-compare:
    - warn
  no-trailing-spaces:
    - warn
  no-unused-vars:
    - warn
    -
      varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  object-curly-spacing:
    - warn
    - always
  quotes:
    - warn
    - single
  semi:
    - error
