frontend:
  endpoint:
    protocol: http
    hostname: localhost # backend host
    port: 3000          # backend port
  cookies:
    key: cashbox_frontend_key
    secure: false # allow cookies only for https

server:
  port: 8080 # frontend port
