module.exports = {
  vendor:          require('./vendor'),
  uglify:          require('./uglify'),
  config:          require('./config'),
  indexHtml:       require('./index-html'),
  devTools:        require('./dev-tools'),
  hotReload:       require('./hot-reload'),
  babelLoader:     require('./babel-loader'),
  stylesLoader:    require('./styles-loader'),
  stylesDevLoader: require('./styles-dev-loader'),
  fontsLoader:     require('./fonts-loader'),
  imagesLoader:    require('./images-loader'),
  reactProduction: require('./react-production'),
  progressBar:     require('./progress-bar'),
}
